
package HerrBD;

import static HerrBD.RestoreMySQL.restoreDB;
import static Notificaciones.DesktopNotify.INFORMATION;
import static Notificaciones.DesktopNotify.showDesktopMessage;
import java.awt.Dimension;
import static java.awt.EventQueue.invokeLater;
import static java.awt.Toolkit.getDefaultToolkit;
import static java.util.logging.Level.SEVERE;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;
import javax.swing.JFrame;
import javax.swing.JProgressBar;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import static necesario.RSAWTUtilities.setOpaque;
import static paneles.pnlConfiguración.existe;


/**
 *
 * @author GNUNIXLOOTER
 */
public final class CargandoRestore extends javax.swing.JDialog {

    /**
     * Creates new form CargandoBackup
     *
     * @param parent
     * @param modal
     */
    public CargandoRestore(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Dimension screenSize = getDefaultToolkit().getScreenSize();
        setBounds(0, 0, screenSize.width, screenSize.height);
        setOpaque(this, false);
        this.setLocationRelativeTo(null);
        this.progreso.setVisible(false);
        startThread();
        
       new Thread(() -> {
            restoreDB("ventas3", "root", "", existe.getAbsolutePath());
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progreso = new javax.swing.JProgressBar();
        msj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        progreso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progresoStateChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setLocationByPlatform(true);
        setUndecorated(true);

        msj.setBackground(new java.awt.Color(51, 51, 51));
        msj.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        msj.setForeground(new java.awt.Color(128, 128, 131));
        msj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msj.setText("Restaurando respaldo de la base de datos...");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HerrBD/carga.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                    .addComponent(msj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msj, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progresoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progresoStateChanged
        if (progreso.getValue() == 30) {
            this.msj.setText("Descomprimiendo respaldo SQL...");
        }
        if (progreso.getValue() == 75) {
            this.msj.setText("Espere un momento...");
        }
        if (progreso.getValue() == 92) {
//            this.icono.setIcon(new ImageIcon(getClass().getResource("/HerrBD/Completo.png")));
            this.msj.setText("Restauración completada.");
        }
        if (progreso.getValue() == 100) {   
            //this.dispose();
            System.exit(0);
            /*showDesktopMessage("Restaurar respaldo...", "Se ha restaurado la base de datos a una fecha anterior, puede que la información"
            + " ya no sea la misma.", INFORMATION, 8000);*/
        }
    }//GEN-LAST:event_progresoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(CargandoRestore.class.getName()).log(SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        invokeLater(() -> {
            CargandoRestore dialog = new CargandoRestore(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    exit(0);
                }

                private void exit(int i) {
                    exit(i); //To change body of generated methods, choose Tools | Templates.
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel msj;
    private javax.swing.JProgressBar progreso;
    // End of variables declaration//GEN-END:variables

    cargarRestore hilo;

    /**
     *
     * @return
     */
    public javax.swing.JProgressBar getProgreso() {
        return progreso;
    }

    /**
     * @param progreso
     */
    public void setProgreso(JProgressBar progreso) {
        this.progreso = progreso;
    }

    void startThread() {
        progreso.setVisible(false);
        hilo = new cargarRestore(getProgreso());
        hilo.start();
        hilo = null;
    }
    private static final Logger LOG = getLogger(CargandoRestore.class.getName());
}
