/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Vistas.Consultar_Credito_Compras;
import Vistas.Consultar_Pagos_Compras;
import Vistas.Factura_Compra;
import Vistas.Factura_Nota_Credito_Compra;

/**
 *
 * @author RojeruSan
 */
public class pnlCompras extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCompras = new javax.swing.JPanel();
        jMenuItem18 = new rojerusan.RSButtonIconI();
        jMenuItem16 = new rojerusan.RSButtonIconI();
        jMenuItem28 = new rojerusan.RSButtonIconI();
        jMenuItem32 = new rojerusan.RSButtonIconI();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlCompras.setBackground(new java.awt.Color(255, 255, 255));

        jMenuItem18.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/compras.png"))); // NOI18N
        jMenuItem18.setText("Registrar compra");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });

        jMenuItem16.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/notasCredito.png"))); // NOI18N
        jMenuItem16.setText("Notas de credito");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });

        jMenuItem28.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/pagosProveedor.png"))); // NOI18N
        jMenuItem28.setText("Pagos a proveedores");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });

        jMenuItem32.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/creditoCompra.png"))); // NOI18N
        jMenuItem32.setText("Credito de Compras");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlComprasLayout = new javax.swing.GroupLayout(pnlCompras);
        pnlCompras.setLayout(pnlComprasLayout);
        pnlComprasLayout.setHorizontalGroup(
            pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuItem16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMenuItem18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMenuItem32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlComprasLayout.createSequentialGroup()
                .addComponent(jMenuItem28, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlComprasLayout.setVerticalGroup(
            pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprasLayout.createSequentialGroup()
                .addComponent(jMenuItem18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 255, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
       new Factura_Compra ().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        new Factura_Nota_Credito_Compra ().setVisible(true); 
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        new Consultar_Pagos_Compras ().setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        new Consultar_Credito_Compras ().setVisible(true);
    }//GEN-LAST:event_jMenuItem32ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI jMenuItem16;
    private rojerusan.RSButtonIconI jMenuItem18;
    private rojerusan.RSButtonIconI jMenuItem28;
    private rojerusan.RSButtonIconI jMenuItem32;
    public static javax.swing.JPanel pnlCompras;
    // End of variables declaration//GEN-END:variables
}
