/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Vistas.Menu_Estadisticas;
import Vistas.Menu_Estadisticas_Compra;
import Vistas.Menu_Reporte_Articulos;
import Vistas.Menu_Reporte_Clientes;
import Vistas.Menu_Reporte_Codigo_Barras;
import Vistas.Menu_Reporte_Compras;
import Vistas.Menu_Reporte_Credito_Compra;
import Vistas.Menu_Reporte_Credito_Venta;
import Vistas.Menu_Reporte_Ventas;
import Vistas.frm_posicionIVA;

/**
 *
 * @author RojeruSan
 */
public class pnlReportes extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReportes = new javax.swing.JPanel();
        rSButtonIconI1 = new rojerusan.RSButtonIconI();
        rSButtonIconI2 = new rojerusan.RSButtonIconI();
        rSButtonIconI3 = new rojerusan.RSButtonIconI();
        rSButtonIconI4 = new rojerusan.RSButtonIconI();
        rSButtonIconI5 = new rojerusan.RSButtonIconI();
        rSButtonIconI6 = new rojerusan.RSButtonIconI();
        rSButtonIconI7 = new rojerusan.RSButtonIconI();
        rSButtonIconI8 = new rojerusan.RSButtonIconI();
        rSButtonIconI9 = new rojerusan.RSButtonIconI();
        rSButtonIconI10 = new rojerusan.RSButtonIconI();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlReportes.setBackground(new java.awt.Color(255, 255, 255));

        rSButtonIconI1.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/ventas.png"))); // NOI18N
        rSButtonIconI1.setText("Ventas");
        rSButtonIconI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI1ActionPerformed(evt);
            }
        });

        rSButtonIconI2.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/creditoFactura.png"))); // NOI18N
        rSButtonIconI2.setText("Crédito de ventas (facturas) ");
        rSButtonIconI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI2ActionPerformed(evt);
            }
        });

        rSButtonIconI3.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/compras.png"))); // NOI18N
        rSButtonIconI3.setText("Compras");
        rSButtonIconI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI3ActionPerformed(evt);
            }
        });

        rSButtonIconI4.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/creditoCompras.png"))); // NOI18N
        rSButtonIconI4.setText("Credito de compras");
        rSButtonIconI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI4ActionPerformed(evt);
            }
        });

        rSButtonIconI5.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/facturacionFinal.png"))); // NOI18N
        rSButtonIconI5.setText("Facturación Final");
        rSButtonIconI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI5ActionPerformed(evt);
            }
        });

        rSButtonIconI6.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/articulos.png"))); // NOI18N
        rSButtonIconI6.setText("Articulos");
        rSButtonIconI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI6ActionPerformed(evt);
            }
        });

        rSButtonIconI7.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/codigoBarra.png"))); // NOI18N
        rSButtonIconI7.setText("Codigos de barra");
        rSButtonIconI7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI7ActionPerformed(evt);
            }
        });

        rSButtonIconI8.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/clientes.png"))); // NOI18N
        rSButtonIconI8.setText("Clientes");
        rSButtonIconI8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI8ActionPerformed(evt);
            }
        });

        rSButtonIconI9.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/estadisticasVentayCompra.png"))); // NOI18N
        rSButtonIconI9.setText("Estadísticas de Venta");
        rSButtonIconI9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI9ActionPerformed(evt);
            }
        });

        rSButtonIconI10.setBackground(new java.awt.Color(78, 184, 221));
        rSButtonIconI10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/estadisticasVentayCompra.png"))); // NOI18N
        rSButtonIconI10.setText("Estadísticas de Compra");
        rSButtonIconI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonIconI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonIconI3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonIconI4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonIconI5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonIconI6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonIconI7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonIconI8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonIconI9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonIconI10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addComponent(rSButtonIconI2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addComponent(rSButtonIconI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconI10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI1ActionPerformed
        Menu_Reporte_Ventas repor = new Menu_Reporte_Ventas();
       repor .setVisible(true);
       //repor.setLocationRelativeTo(this);
    }//GEN-LAST:event_rSButtonIconI1ActionPerformed

    private void rSButtonIconI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI2ActionPerformed
        Menu_Reporte_Credito_Venta credito = new Menu_Reporte_Credito_Venta();
        credito.setVisible(true);
    }//GEN-LAST:event_rSButtonIconI2ActionPerformed

    private void rSButtonIconI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI3ActionPerformed
        Menu_Reporte_Compras repor = new Menu_Reporte_Compras();
       repor .setVisible(true);
       //repor.setLocationRelativeTo(this);
    }//GEN-LAST:event_rSButtonIconI3ActionPerformed

    private void rSButtonIconI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI4ActionPerformed
        Menu_Reporte_Credito_Compra credito = new Menu_Reporte_Credito_Compra();
        credito.setVisible(true);
    }//GEN-LAST:event_rSButtonIconI4ActionPerformed

    private void rSButtonIconI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI5ActionPerformed
        frm_posicionIVA repor = new frm_posicionIVA();
       repor .setVisible(true);
       repor.setLocationRelativeTo(this);
    }//GEN-LAST:event_rSButtonIconI5ActionPerformed

    private void rSButtonIconI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI6ActionPerformed
         Menu_Reporte_Articulos articulo = new Menu_Reporte_Articulos();
       articulo.setVisible(true); 
    }//GEN-LAST:event_rSButtonIconI6ActionPerformed

    private void rSButtonIconI7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI7ActionPerformed
         Menu_Reporte_Codigo_Barras articulo = new Menu_Reporte_Codigo_Barras();
        articulo.setVisible(true); 
    }//GEN-LAST:event_rSButtonIconI7ActionPerformed

    private void rSButtonIconI8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI8ActionPerformed
        Menu_Reporte_Clientes cliente = new Menu_Reporte_Clientes();
       cliente.setVisible(true); 
    }//GEN-LAST:event_rSButtonIconI8ActionPerformed

    private void rSButtonIconI9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI9ActionPerformed
       new Menu_Estadisticas ().setVisible(true);
    }//GEN-LAST:event_rSButtonIconI9ActionPerformed

    private void rSButtonIconI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI10ActionPerformed
        new Menu_Estadisticas_Compra ().setVisible(true);
    }//GEN-LAST:event_rSButtonIconI10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel pnlReportes;
    private rojerusan.RSButtonIconI rSButtonIconI1;
    private rojerusan.RSButtonIconI rSButtonIconI10;
    private rojerusan.RSButtonIconI rSButtonIconI2;
    private rojerusan.RSButtonIconI rSButtonIconI3;
    private rojerusan.RSButtonIconI rSButtonIconI4;
    private rojerusan.RSButtonIconI rSButtonIconI5;
    private rojerusan.RSButtonIconI rSButtonIconI6;
    private rojerusan.RSButtonIconI rSButtonIconI7;
    private rojerusan.RSButtonIconI rSButtonIconI8;
    private rojerusan.RSButtonIconI rSButtonIconI9;
    // End of variables declaration//GEN-END:variables
}
