/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Vistas.Consultar_Credito_Ventas;
import Vistas.Consultar_Pagos_Ventas;
import Vistas.Factura_Nota_Credito_Venta;
import Vistas.Factura_Presupuesto;
import Vistas.Factura_Venta;
import Vistas.Menu_Remitos;
import Vistas.Modulo_Saldos;

/**
 *
 * @author RojeruSan
 */
public class pnlVentas extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVentas = new javax.swing.JPanel();
        Facturas = new rojerusan.RSButtonIconI();
        jMenuItem10 = new rojerusan.RSButtonIconI();
        jMenuItem11 = new rojerusan.RSButtonIconI();
        jMenuItem19 = new rojerusan.RSButtonIconI();
        jMenuItem8 = new rojerusan.RSButtonIconI();
        jMenuItem23 = new rojerusan.RSButtonIconI();
        jMenuItem30 = new rojerusan.RSButtonIconI();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlVentas.setBackground(new java.awt.Color(255, 255, 255));

        Facturas.setBackground(new java.awt.Color(78, 184, 221));
        Facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/registrarVenta.png"))); // NOI18N
        Facturas.setText("Registrar venta");
        Facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturasActionPerformed(evt);
            }
        });

        jMenuItem10.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/remitos.png"))); // NOI18N
        jMenuItem10.setText("Remitos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });

        jMenuItem11.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/presupuestos.png"))); // NOI18N
        jMenuItem11.setText("Presupuestos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });

        jMenuItem19.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/notasCredito.png"))); // NOI18N
        jMenuItem19.setText("Notas de credito");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });

        jMenuItem8.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/creditoVenta.png"))); // NOI18N
        jMenuItem8.setText("Creditos de remitos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });

        jMenuItem23.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/clientes.png"))); // NOI18N
        jMenuItem23.setText("Pagos de clientes");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });

        jMenuItem30.setBackground(new java.awt.Color(78, 184, 221));
        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_principal/creditoFactura.png"))); // NOI18N
        jMenuItem30.setText("Credito de facturas");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jMenuItem10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jMenuItem11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jMenuItem19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jMenuItem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jMenuItem23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jMenuItem30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addComponent(Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuItem30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
       new Consultar_Credito_Ventas ().setVisible(true);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void FacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturasActionPerformed
        new Factura_Venta ().setVisible(true); 
    }//GEN-LAST:event_FacturasActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       new Menu_Remitos ().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new Factura_Presupuesto ().setVisible(true); 
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new Factura_Nota_Credito_Venta ().setVisible(true);  
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new Modulo_Saldos ().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        new Consultar_Pagos_Ventas ().setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI Facturas;
    private rojerusan.RSButtonIconI jMenuItem10;
    private rojerusan.RSButtonIconI jMenuItem11;
    private rojerusan.RSButtonIconI jMenuItem19;
    private rojerusan.RSButtonIconI jMenuItem23;
    private rojerusan.RSButtonIconI jMenuItem30;
    private rojerusan.RSButtonIconI jMenuItem8;
    public static javax.swing.JPanel pnlVentas;
    // End of variables declaration//GEN-END:variables
}
